### ISSUE TITLE
Non-NCBI Fasta file analysis

### ISSUE THREAD

**Issue by Dfvandenberg** [kew222/Self-Targeting-Spacer-Searcher#5]
I am trying to analyze some non-NCBI fasta files and giving the .gb file within the same folder using the --dir option.
This genbank file was made by prokka in compliant mode and the locus tag is the same as the file name (thought that that would do the trick), but it doesn't get far.
It says that the accession number is not on NCBI and there is no corresponding genbank file.

**Comment by kew222** [comment]
The current code actually is only written to accept .fasta files with the "--provided" mode, and basically does everything it can to find an Accession number to pull Genbanks from NCBI. I'll modify the code to take Genbanks instead and just use them locally (how I probably would have done it in retrospect), but it might take me a little while since I'm not actively working on anti-CRISPRs anymore.

**Comment by kew222** [comment]
Hi @Dfvandenberg ,

Sorry for the long turnaround time on this, but I've made some code updates. While it's definitely working now, I think was before, and the confusion was probably in that the script is expecting to find the genbank files in GenBank_files/ (which is normally created during the file download from NCBI), but I didn't make a clear error message that that was the case (have since). 

Since it was pretty much working out of box after upgrading to Python 3, I didn't spend the time to add an option to define the genbank file location.
